display_name = "ge-alert-policy"
project   =   ""
combiner = "OR"
condition_name   =  "test condition"
filter  = "metric.type=\"compute.googleapis.com/instance/cpu/utilization\" AND  resource.type=\"gce_instance\""
duration = "60s"
threshold_value  = "80"
comparison  = "COMPARISON_GT"
alignment_period = "60s"
per_series_aligner   = "ALIGN_NONE"
notification_channel_name = "ge-monitoring-notification-channel"
email_address = ""
#number   =  "+91 1234567890"