# openapi2-functions.yaml
swagger: '2.0'
info:
  title: testapi
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /func-genone-01:
    get:
      summary: func-genone-01
      operationId: func-genone-01
      x-google-backend:
        address: https://<func-region>-<project-id>.cloudfunctions.net/func-genone-01
      responses:
        '200':
          description: A successful response
          schema:
            type: string

  
